In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

1.1 

Se carga el dataset para poder trabajar con el

In [54]:
df = pd.read_csv('ventas_historicas.csv')
df

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
1,1002,Enero,Oeste,Carlos Rivas,Laptop,Online,4,894.32,0.0,3577.28
2,1003,Abril,Oeste,Laura Diaz,Tablet,Online,13,375.14,15.0,4876.82
3,1004,Enero,Este,Camila Vega,Laptop,Online,6,1010.65,NaN,6063.90
4,1005,Enero,Norte,Laura Diaz,Teclado,NaN,10,78.27,0.0,782.70
...,...,...,...,...,...,...,...,...,...,...
295,1296,Abril,Sur,Carlos Rivas,Teclado,Online,8,71.84,0.0,574.72
296,1297,Abril,Este,Camila Vega,Tablet,Tienda fisica,9,359.42,20.0,3234.78
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18
298,1299,Junio,Oeste,Camila Vega,Teclado,Online,11,69.20,10.0,761.20
299,1300,Mayo,Sur,Javier Munoz,Tablet,Tienda fisica,10,353.19,20.0,3531.90

1.1

Primero se ven la dimensiones y tipos del dataset
Luego se imprimen las 5 primeras filas
Se verifica cuantos valores nulos tiene cada columna

In [53]:
print("Shape:", df.shape)
print("Tipos de datos:\n", df.dtypes)

print("\nPrimeras 5 filas")
display(df.head())

print("\nValores Nulos")
print(df.isnull().sum())

Shape: (300, 10)
Tipos de datos:
 id_venta         int64
mes                str
region             str
vendedor           str
categoria          str
canal              str
cantidad         int64
precio_unit    float64
descuento      float64
monto_bruto    float64
dtype: object

Primeras 5 filas

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
1,1002,Enero,Oeste,Carlos Rivas,Laptop,Online,4,894.32,0.0,3577.28
2,1003,Abril,Oeste,Laura Diaz,Tablet,Online,13,375.14,15.0,4876.82
3,1004,Enero,Este,Camila Vega,Laptop,Online,6,1010.65,NaN,6063.90
4,1005,Enero,Norte,Laura Diaz,Teclado,NaN,10,78.27,0.0,782.70

Valores Nulos
id_venta        0
mes             0
region          0
vendedor       21
categoria       0
canal          11
cantidad        0
precio_unit     0
descuento      11
monto_bruto     0
dtype: int64

1.2

Se filtran las ventas de "centro" de la  columna Region que tengan un monto bruto mayor a 300

In [46]:
filtro_centro = df[(df['region'] == 'Centro') & (df['monto_bruto'] > 300)]
print(f"Filas región Centro con monto > $300: {len(filtro_centro)}")

Filas región Centro con monto > $300: 47

1.3

filtra las ventas del canal online cuyo descuento sea igual o mayor a 15 mostrando solo las columnas "region, categoria, cantidad, monto_bruto, descuento"

In [43]:
filtro_online = df[(df['canal'] == 'Online') & (df['descuento'] >= 15)]
display(filtro_online[['region', 'categoria', 'cantidad', 'monto_bruto', 'descuento']])

     region    categoria  cantidad  monto_bruto  descuento
2     Oeste       Tablet        13      4876.82       15.0
5       Sur      Monitor         7      1951.18       15.0
7    Centro       Tablet         4      1508.76       20.0
20    Norte  Auriculares         7       958.65       20.0
23    Oeste       Laptop         7      5688.69       20.0
36      Sur       Tablet        12      4683.96       20.0
48    Oeste      Teclado        11       804.43       20.0
49      Sur       Tablet         9      2735.10       20.0
60    Oeste  Auriculares        10      1311.50       15.0
70    Norte  Auriculares        12      1532.64       20.0
90    Oeste      Monitor         5      1653.60       20.0
112    Este       Tablet        14      4457.88       15.0
132   Oeste        Mouse         5       214.90       20.0
133   Norte      Teclado         3       195.42       15.0
149   Oeste       Tablet         2       619.72       20.0
159    Este       Tablet         4      1302.96       20.0
179  Centro  Auriculares         7       882.98       20.0
191  Centro      Monitor         2       584.38       20.0
204  Centro       Tablet         2       649.80       15.0
228    Este  Auriculares         5       600.35       20.0
237  Centro  Auriculares        14      1876.98       20.0
282     Sur  Auriculares        10      1323.60       15.0
289     Sur        Mouse         1        39.49       20.0
297  Centro       Laptop         1      1036.18       20.0

1.4 

filtra las ventas donde la categoria sea "Laptop, Tablet" y se muestra la cantidad de filas

In [44]:
filtro_tech = df[df['categoria'].isin(['Laptop', 'Tablet'])]
print(f"\nFilas de Laptop o Tablet: {len(filtro_tech)}")

Filas de Laptop o Tablet: 97

1.5

filtra las ventas con cantidad entre 8 y 15 unidades y muestra las primeras 10 filas ordenadas de mayor a menor usando el monto bruto

In [61]:
filtro_cantidad = df[df['cantidad'].between(8, 15)]
display(filtro_cantidad.sort_values(by='monto_bruto', ascending=False).head(10))

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
25,1026,Mayo,Norte,NaN,Laptop,Mayorista,15,1012.42,0.0,15186.30
207,1208,Abril,Sur,Roberto Fuentes,Laptop,NaN,15,977.16,20.0,14657.40
88,1089,Junio,Oeste,Maria Lopez,Laptop,Tienda fisica,15,966.15,10.0,14492.25
47,1048,Febrero,Norte,Roberto Fuentes,Laptop,Mayorista,14,983.79,5.0,13773.06
11,1012,Junio,Centro,Carlos Rivas,Laptop,Mayorista,15,905.07,0.0,13576.05
223,1224,Junio,Norte,Camila Vega,Laptop,Mayorista,13,1040.82,0.0,13530.66
94,1095,Junio,Oeste,NaN,Laptop,Tienda fisica,14,945.13,0.0,13231.82
165,1166,Febrero,Sur,Ana Torres,Laptop,Tienda fisica,15,827.93,5.0,12418.95
171,1172,Febrero,Oeste,Carlos Rivas,Laptop,Online,13,941.86,0.0,12244.18
245,1246,Febrero,Este,Maria Lopez,Laptop,Mayorista,14,857.92,0.0,12010.88

¿Por qué en Pandas se usan & y | en lugar de and y or para combinar condiciones?

Porque and y or evalúan el valor de verdad de todo el objeto a la vez, lo cual genera un error en estructuras grandes. Los símbolos & y | permiten a Pandas realizar operaciones lógicas "elemento por elemento" (fila por fila) de forma vectorizada.

¿Que ventaja tiene .isin() frente a escribir multiples condiciones con |?

La sintaxis es mucho más limpia, fácil de leer y permite agregar múltiples elementos a una lista sin tener que repetir el nombre de la columna y el operador == varias veces.

2.1

filtra las ventas realizadas en enero o febrero donde la categoria sea "laptop, tablet" y el descuento sea mayor a 10

In [64]:
filtro_e_f = df[
    (df['mes'].isin(['Enero', 'Febrero'])) & 
    (df['categoria'].isin(['Laptop', 'Tablet'])) & 
    (df['descuento'] > 10)
]
print(filtro_e_f)

     id_venta      mes  region         vendedor categoria          canal  \
15       1016  Febrero  Centro  Roberto Fuentes    Tablet      Mayorista
23       1024  Febrero   Oeste      Camila Vega    Laptop         Online
149      1150  Febrero   Oeste      Maria Lopez    Tablet         Online
157      1158  Febrero    Este       Ana Torres    Tablet  Tienda fisica
187      1188  Febrero   Oeste     Javier Munoz    Tablet      Mayorista
297      1298    Enero  Centro       Laura Diaz    Laptop         Online

     cantidad  precio_unit  descuento  monto_bruto
15          3       305.93       20.0       917.79
23          7       812.67       20.0      5688.69
149         2       309.86       20.0       619.72
157        15       378.21       15.0      5673.15
187        12       312.03       20.0      3744.36
297         1      1036.18       20.0      1036.18

2.2

Utilizando el filtro anterior se identifican los 5 registros con mayor monto bruto

In [69]:
display(filtro_e_f.nlargest(5, 'monto_bruto'))

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
23,1024,Febrero,Oeste,Camila Vega,Laptop,Online,7,812.67,20.0,5688.69
157,1158,Febrero,Este,Ana Torres,Tablet,Tienda fisica,15,378.21,15.0,5673.15
187,1188,Febrero,Oeste,Javier Munoz,Tablet,Mayorista,12,312.03,20.0,3744.36
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18
15,1016,Febrero,Centro,Roberto Fuentes,Tablet,Mayorista,3,305.93,20.0,917.79

2.3

Se crea un filtro para las ventas de norte o sur con unidades mayor o igual a 10 y un monto bruto superior al promedio del monto bruto del dataset

In [79]:
promedio_general_monto_bruto = df['monto_bruto'].mean()
print(f'promedio general de monto bruto del dataset: {promedio_general_monto_bruto}')

filtro_comparativo = df[
    (df['region'].isin(['Norte', 'Sur'])) & 
    (df['cantidad'] >= 10) & 
    (df['monto_bruto'] > promedio_general_monto_bruto)
]
print(filtro_comparativo)

promedio general de monto bruto del dataset: 2431.0863999999997
     id_venta      mes region         vendedor categoria          canal  \
25       1026     Mayo  Norte              NaN    Laptop      Mayorista
36       1037    Abril    Sur       Ana Torres    Tablet         Online
37       1038  Febrero    Sur     Carlos Rivas   Monitor  Tienda fisica
42       1043    Abril    Sur     Carlos Rivas   Monitor      Mayorista
46       1047     Mayo  Norte     Javier Munoz   Monitor         Online
47       1048  Febrero  Norte  Roberto Fuentes    Laptop      Mayorista
59       1060  Febrero  Norte       Pedro Soto    Laptop         Online
62       1063    Junio    Sur       Laura Diaz    Laptop      Mayorista
75       1076     Mayo    Sur      Camila Vega    Laptop      Mayorista
114      1115    Marzo  Norte       Pedro Soto    Laptop         Online
115      1116  Febrero    Sur       Ana Torres   Monitor  Tienda fisica
116      1117    Enero  Norte     Javier Munoz    Tablet         Online
123      1124    Abril  Norte     Carlos Rivas    Laptop      Mayorista
165      1166  Febrero    Sur       Ana Torres    Laptop  Tienda fisica
207      1208    Abril    Sur  Roberto Fuentes    Laptop            NaN
211      1212  Febrero  Norte  Roberto Fuentes    Tablet  Tienda fisica
223      1224    Junio  Norte      Camila Vega    Laptop      Mayorista
225      1226     Mayo  Norte       Laura Diaz    Tablet         Online
264      1265    Abril  Norte     Carlos Rivas   Monitor         Online
266      1267    Marzo  Norte     Carlos Rivas    Laptop      Mayorista
281      1282    Abril  Norte       Ana Torres    Tablet  Tienda fisica
299      1300     Mayo    Sur     Javier Munoz    Tablet  Tienda fisica

     cantidad  precio_unit  descuento  monto_bruto
25         15      1012.42        0.0     15186.30
36         12       390.33       20.0      4683.96
37         14       250.99        5.0      3513.86
42         15       284.80        0.0      4272.00
46         14       356.93        0.0      4997.02
47         14       983.79        5.0     13773.06
59         10       774.31        0.0      7743.10
62         10       996.38       20.0      9963.80
75         10       991.35        0.0      9913.50
114        13       914.46        0.0     11887.98
115        14       360.65        0.0      5049.10
116        10       313.44        0.0      3134.40
123        12       849.20        0.0     10190.40
165        15       827.93        5.0     12418.95
207        15       977.16       20.0     14657.40
211        15       303.75        0.0      4556.25
223        13      1040.82        0.0     13530.66
225        14       389.30       10.0      5450.20
264        14       355.62        0.0      4978.68
266        13       778.38       15.0     10118.94
281        14       355.95       15.0      4983.30
299        10       353.19       20.0      3531.90

2.4

Usando el filtro del paso 3, cuenta y compara cuantas ventas existen por region entre norte y sur, primero usando el filtro de cantidad minima, luego sin usar el filtro de cantidad minima

In [87]:
print('\n con filtro')
print(filtro_comparativo['region'].value_counts())
print('\n sin filtro')
filtro_sin_cantidad = df[(df['region'].isin(['Norte', 'Sur'])) & (df['monto_bruto'] > promedio_general_monto_bruto)]
print(filtro_sin_cantidad['region'].value_counts())

 con filtro
region
Norte    13
Sur       9
Name: count, dtype: int64

 sin filtro
region
Norte    17
Sur      13
Name: count, dtype: int64

2.5

Crea una función Python que reciba como parámetros: region, categoria y monto_minimo,
y retorne el DataFrame filtrado según esos criterios. Se usan 3 diferentes parametros y se usa head para mostrar las 3 primeras filas

In [90]:
def filtrar_ventas(region, categoria, monto_minimo):
    return df[
        (df['region'] == region) & 
        (df['categoria'] == categoria) & 
        (df['monto_bruto'] >= monto_minimo)
    ]

display(filtrar_ventas('Norte', 'Laptop', 1000).head(3))
display(filtrar_ventas('Sur', 'Tablet', 500).head(3))
display(filtrar_ventas('Centro', 'Laptop', 800).head(3))

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
25,1026,Mayo,Norte,NaN,Laptop,Mayorista,15,1012.42,0.0,15186.30
47,1048,Febrero,Norte,Roberto Fuentes,Laptop,Mayorista,14,983.79,5.0,13773.06

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
36,1037,Abril,Sur,Ana Torres,Tablet,Online,12,390.33,20.0,4683.96
49,1050,Junio,Sur,Roberto Fuentes,Tablet,Online,9,303.90,20.0,2735.10
138,1139,Enero,Sur,Maria Lopez,Tablet,Tienda fisica,4,294.21,0.0,1176.84

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
11,1012,Junio,Centro,Carlos Rivas,Laptop,Mayorista,15,905.07,0.0,13576.05
30,1031,Junio,Centro,Laura Diaz,Laptop,Mayorista,2,1041.74,0.0,2083.48
127,1128,Mayo,Centro,Laura Diaz,Laptop,NaN,3,815.41,20.0,2446.23

3.1

Agrupa el dataset por 'region' y calcula para la columna monto_bruto: suma total,
promedio, máximo, mínimo y conteo de transacciones. Usa .agg() con nombres de
columnas personalizados y aplica. round(2).

In [92]:
resumen_region = df.groupby('region')['monto_bruto'].agg(
    Suma_Total='sum',
    Promedio='mean',
    Maximo='max',
    Minimo='min',
    Conteo='count'
)
display(resumen_region)

        Suma_Total     Promedio    Maximo  Minimo  Conteo
region
Centro   110254.74  1934.293684  13576.05   34.07      57
Este     147358.93  2585.244386  12010.88   69.24      57
Norte    167154.38  2932.532982  15186.30   33.77      57
Oeste    183789.62  2588.586197  14492.25   31.32      71
Sur      120768.25  2082.211207  14657.40   34.20      58


3.2

Sobre el resultado anterior, usa .reset_index() y ordena de mayor a menor según el total de
ventas. Muestra el DataFrame resultante.

In [93]:
resumen_region.round(2).reset_index().sort_values(by='Suma_Total', ascending=False)

   region  Suma_Total  Promedio    Maximo  Minimo  Conteo
3   Oeste   183789.62   2588.59  14492.25   31.32      71
2   Norte   167154.38   2932.53  15186.30   33.77      57
1    Este   147358.93   2585.24  12010.88   69.24      57
4     Sur   120768.25   2082.21  14657.40   34.20      58
0  Centro   110254.74   1934.29  13576.05   34.07      57

3.3

Agrupa por ['region', 'mes'] y calcula la suma de monto_bruto y la suma de cantidad. Usa
reset_index() al final. Muestra las primeras 10 filas.

In [96]:
resumen_mes = df.groupby(['region', 'mes'])[['monto_bruto', 'cantidad']].sum().reset_index()
display(resumen_mes.head(10))

   region      mes  monto_bruto  cantidad
0  Centro    Abril     10390.50        64
1  Centro    Enero      8727.16        33
2  Centro  Febrero      6330.77        37
3  Centro    Junio     51903.36       120
4  Centro    Marzo     16884.87        81
5  Centro     Mayo     16018.08        62
6    Este    Abril     29469.73       111
7    Este    Enero     21131.64        64
8    Este  Febrero     25411.30        56
9    Este    Junio     25126.33        60

3.4

Identifica el vendedor con mayor suma de monto_bruto (ignorando nulos con dropna=False
por defecto en groupby). Usa .groupby('vendedor')['monto_bruto'].sum().idxmax() para
encontrar el nombre directamente.

In [98]:
mejor_vendedor = df.groupby('vendedor', dropna=False)['monto_bruto'].sum().idxmax()
print(f"El vendedor con mayor suma total es: {mejor_vendedor}")

El vendedor con mayor suma total es: Camila Vega

3.5

Agrupa por categoría y calcula el precio_unit promedio y la cantidad total. Ordena por
precio promedio descendente e interpreta el resultado: ¿que categoría tiene el mayor
ticket promedio?

In [100]:
resumen_cat = df.groupby('categoria').agg(
    precio_promedio=('precio_unit', 'mean'),
    cantidad_total=('cantidad', 'sum')
).sort_values(by='precio_promedio', ascending=False)
display(resumen_cat)

             precio_promedio  cantidad_total
categoria
Laptop            905.985510             428
Tablet            332.038750             405
Monitor           307.310000             333
Auriculares       126.983051             516
Teclado            68.887593             445
Mouse              36.549778             271

¿Para qué sirve .reset_index() después de un groupby? ¿Qué sucede si no lo aplicas? 

Sirve para aplanar el índice jerárquico que crea el groupby y convertirlo de nuevo en columnas normales del DataFrame. Si no se aplica, las variables agrupadas (como la región o el mes) quedan "atrapadas" como el índice de la tabla, dificultando su uso en filtros posteriores.

¿Cuándo es preferible .agg() con nombres vs. usar .sum(), .mean() directamente?

Es preferible usar .agg() cuando necesitas calcular múltiples métricas estadísticas distintas (como suma, promedio y máximo) sobre la misma columna en un solo paso, y además te permite asignarles nombres limpios y profesionales al instante.

4.1

Crea una tabla pivote usando pd.pivot_table() con: indice = 'region', columnas = 'mes',
valores = 'monto_bruto', funcion de agregación = suma. Aplica .round(2) al resultado.

In [104]:
pivot_mensual = pd.pivot_table(
    df, 
    index='region', 
    columns='mes', 
    values='monto_bruto', 
    aggfunc='sum'
).round(2)

4.2

la tabla pivote, usa .fillna(0) para reemplazar los valores NaN por 0. Explica en
Markdown por que pueden existir NaN en una pivot_table.

In [107]:
pivot_mensual.fillna(0, inplace=True)

mes        Abril     Enero   Febrero     Junio     Marzo      Mayo
region
Centro  10390.50   8727.16   6330.77  51903.36  16884.87  16018.08
Este    29469.73  21131.64  25411.30  25126.33  13920.69  32299.24
Norte   29019.38   5588.67  29335.57  42657.28  27532.04  33021.44
Oeste   35644.34  16936.80  57842.95  33062.70  16948.56  23354.27
Sur     33201.05  15321.54  21079.02  15081.79   9099.19  26985.66

4.3

Agrega una columna de totales al final de la tabla pivote usando pivot['Total'] =
pivot.sum(axis=1). ¿Cuál es la región con mayor total semestral?

In [110]:
pivot_mensual['Total'] = pivot_mensual.sum(axis=1)
display(pivot_mensual)

mes        Abril     Enero   Febrero     Junio     Marzo      Mayo      Total
region
Centro  10390.50   8727.16   6330.77  51903.36  16884.87  16018.08  220509.48
Este    29469.73  21131.64  25411.30  25126.33  13920.69  32299.24  294717.86
Norte   29019.38   5588.67  29335.57  42657.28  27532.04  33021.44  334308.76
Oeste   35644.34  16936.80  57842.95  33062.70  16948.56  23354.27  367579.24
Sur     33201.05  15321.54  21079.02  15081.79   9099.19  26985.66  241536.50

4.4

Aplica formato de estilo con pivot.style.format('${:,.2f}').highlight_max(axis=0, color='#E8F8F5')
para resaltar el maximo de cada mes por columna.

In [112]:
display(pivot_mensual.style.format('${:.2f}').highlight_max(axis=0, color='#E8F8F5'))

4.5

Crea una segunda pivot_table donde el indice sea 'categoria' y las columnas sean 'canal'.
Usa aggfunc='count' para contar el numero de transacciones por combinación. ¿Que
canal tiene mas ventas para
Laptops?

In [115]:
pivot_canal = pd.pivot_table(
    df,
    index='categoria',
    columns='canal',
    values='monto_bruto', # Se puede usar cualquier columna, aggfunc='count' solo cuenta filas
    aggfunc='count'
).fillna(0)
display(pivot_canal)

canal        Mayorista  Online  Tienda fisica
categoria
Auriculares         16      24             17
Laptop              17      13             16
Monitor             12      17             15
Mouse               13      12             19
Tablet              16      14             18
Teclado             18      18             14